spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fsu-itec442-ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Paradise@0
  jpa:
    hibernate:
      ddl-auto: update